WITH
LIST AS (
    SELECT * FROM AIRBNB.PROD.dim_listings_cleansed
),
HOST AS (
    SELECT * FROM  AIRBNB.PROD.dim_hosts_cleansed_v2
)

SELECT
L.LISTING_ID,
L.LISTING_NAME,
L.ROOM_TYPE,
L.MINIMUM_NIGHTS,
L.PRICE,
L.HOST_ID,
H.HOST_NAME,
H.IS_SUPERHOST AS HOST_IS_SUPERHOST,
L.CREATED_AT,
GREATEST(L.UPDATED_AT,H.UPDATED_AT) AS UPDATED_AT
FROM LIST L
LEFT JOIN HOST H ON (L.HOST_ID = H.HOST_ID)