
WITH  __dbt__cte__src_hosts as (
WITH RAW_HOSTS AS 
(
    --SELECT * FROM AIRBNB.RAW.RAW_HOSTS
    SELECT * FROM AIRBNB.raw.raw_hosts
)

SELECT 
  ID AS HOST_ID,
  NAME AS HOST_NAME,
  IS_SUPERHOST,
  CREATED_AT,
  UPDATED_AT
FROM RAW_HOSTS
ORDER BY ID
), SRC_HOSTS AS 
(
    SELECT * FROM __dbt__cte__src_hosts
)
SELECT 
    HOST_ID,
    NVL(HOST_NAME,'ANONYMOUS') AS HOST_NAME,
    IS_SUPERHOST,
    CREATED_AT,
    UPDATED_AT
FROM SRC_HOSTS