
WITH  __dbt__cte__src_listings as (
WITH raw_listing AS 
(
    --SELECT * FROM AIRBNB.RAW.RAW_LISTINGS
    SELECT * FROM AIRBNB.raw.raw_listings
) 

SELECT 
    ID AS LISTING_ID,
    NAME AS LISTING_NAME,
    LISTING_URL,
    ROOM_TYPE,
    MINIMUM_NIGHTS,
    HOST_ID,
    PRICE AS PRICE_STR,
    CREATED_AT,
    UPDATED_AT
FROM RAW_LISTING
--WHERE
--MINIMUM_NIGHTS > 100
--UPPER(ROOM_TYPE) LIKE 'ENTIRE%'
ORDER BY ID ASC
), SRC_LISTINGS AS 
(
    SELECT * FROM __dbt__cte__src_listings
)
SELECT 
    LISTING_ID,
    LISTING_NAME,
    ROOM_TYPE,
    LISTING_URL,
    CASE 
        WHEN MINIMUM_NIGHTS = 0 THEN 1
        ELSE MINIMUM_NIGHTS
    END AS MINIMUM_NIGHTS,
    HOST_ID,
    REPLACE(PRICE_STR,'$') :: NUMBER(10,2) AS PRICE,
    CREATED_AT,
    UPDATED_AT 
FROM SRC_LISTINGS
ORDER BY LISTING_ID