WITH raw_listing AS 
(
    --SELECT * FROM AIRBNB.RAW.RAW_LISTINGS
    SELECT * FROM AIRBNB.raw.raw_listings
) 

SELECT 
    ID AS LISTING_ID,
    NAME AS LISTING_NAME,
    LISTING_URL,
    ROOM_TYPE,
    MINIMUM_NIGHTS,
    HOST_ID,
    PRICE AS PRICE_STR,
    CREATED_AT,
    UPDATED_AT
FROM RAW_LISTING
--WHERE
--MINIMUM_NIGHTS > 100
--UPPER(ROOM_TYPE) LIKE 'ENTIRE%'
ORDER BY ID ASC